project:
  type: website

website:
  title: "simple_quarto_website"
  navbar:
    left:
      - href: index.ipynb
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    toc: true



