project:
  type: website

website:
  title: "simple_quarto_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.ipynb
      - slides/slides.ipynb

bibliography: reference.bib
bibliographystyle: apa

format:
  html:
    theme: cosmo
    toc: true



